apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  collector:
    replicas: 1
    options:
      # default is 50
      collector.num-workers: 20
      # default is 2000
      # for 400k memory is ~1463Mi
      collector.queue-size: 4000
      es.num-shards: 3
      es.num-replicas: 1
      # default 1
      es.bulk.workers: 150
      # default 5000000
      es.bulk.size: 5000000
      # default 1000
      es.bulk.actions: 1000
      # default 200ms
      es.bulk.flush-interval: 200ms
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://opensearch-cluster-master:9200
