apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://opensearch-cluster-master:9200
