apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  collector:
    replicas: 3
    options:
        collector.num-workers: 100
        collector.queue-size: 4000
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://opensearch-cluster-master:9200
