apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  collector:
    replicas: 5
    options:
        collector.num-workers: 1000
        # for 400k memory is ~1463Mi
        collector.queue-size: 400000
        es.num-shards: 3
        es.num-replicas: 1
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://opensearch-cluster-master:9200
