---
memcached:
  enabled: false
traces:
  jaeger:
    thriftHttp:
      enabled: true
tempo:
  structuredConfig:
    overrides:
      ingestion_burst_size_bytes: 15000000000
      ingestion_rate_limit_bytes: 15000000000
      max_traces_per_user: 50000000
      max_bytes_per_tag_values_query: 15000000000
ingester:
  replicas: 2
  config:
    replication_factor: 1
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
  limits:
    cpu: "100m"
    memory: "400Mi"
distributor:
  replicas: 2
  affinity: {}
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
  limits:
    cpu: "100m"
    memory: "400Mi"
querier:
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
  limits:
    cpu: "100m"
    memory: "400Mi"
storage:
  trace:
    backend: "s3"
    s3:
      access_key: tempo
      bucket: tempo
      endpoint: minio:9000
      insecure: true
      secret_key: supersecret
