---
memcached:
  enabled: false
search:
  enabled: true
traces:
  jaeger:
    thriftHttp:
      enabled: true
tempo:
  structuredConfig:
    query_frontend:
      search:
        max_duration: 72h0m0s
    overrides:
      ingestion_burst_size_bytes: 15000000000
      ingestion_rate_limit_bytes: 15000000000
      max_traces_per_user: 50000000
      max_bytes_per_tag_values_query: 15000000000
ingester:
  replicas: 1
  config:
    replication_factor: 1
  resources:
    requests:
      cpu: 1000m
      memory: 1500Mi
    limits:
      cpu: "1000m"
      memory: "1500Mi"
distributor:
  replicas: 1
  affinity: {}
  resources:
    requests:
      cpu: 1000m
      memory: 1500Mi
    limits:
      cpu: "1000m"
      memory: "1500Mi"
querier:
  resources:
    requests:
      cpu: 800m
      memory: 500Mi
    limits:
      cpu: "800m"
      memory: "500Mi"
queryFrontend:
  resources:
    requests:
      cpu: 200m
      memory: 120Mi
    limits:
      cpu: "200m"
      memory: "120Mi"
storage:
  trace:
    backend: "s3"
    s3:
      access_key: tempo
      bucket: tempo
      endpoint: minio.minio.svc:9000
      insecure: true
      secret_key: supersecret
